# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# Adapted from https://github.com/LGUG2Z/komorebi/blob/e240bc770619fa7c1f311b8a376551f2dde8a2d7/.goreleaser.yml
project_name: ouverture

before:
  hooks:
    - bash -c 'echo "package main; func main() {}" > dummy.go'

builds:
  - id: ouverture
    binary: ovt
    main: dummy.go
    # env:
    #   - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true
    id: ouverture
    hooks:
      post:
        - mkdir -p ./dist/ouverture_darwin_all
        - bash -c 'cp "$(swift build --show-bin-path -c release --arch arm64 --arch x86_64)/ovt" ./dist/ouverture_darwin_all/ovt'

archives:
  - format: tar.gz
    # https://goreleaser.com/customization/archive/#packaging-only-the-binaries
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "all" }}universal2
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      # Use zip for windows archives
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  # https://goreleaser.com/customization/homebrew/
  - homepage: https://github.com/rami3l/Ouverture
    description: A default application modifier for macOS.
    license: BSD-2-Clause

    install: |
      bin.install "ovt"

    test: |
      system "#{bin}/ovt"

    skip_upload: auto

    # https://github.com/goreleaser/goreleaser/blob/a0f0d01a8143913cde72ebc1248abef089ae9b27/.goreleaser.yaml#L211
    repository:
      owner: rami3l
      name: homebrew-tap
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: rami3l
          name: homebrew-tap
          branch: master
