name: publish

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, '-') }}

  publish:
    name: Publish for ${{ matrix.os }}
    needs: [create-release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1

      # https://liamnichols.eu/2020/08/01/building-swift-packages-as-a-universal-binary.html
      - name: Build
        run: |
          swift build -c release --arch arm64 --arch x86_64

      # https://goreleaser.com/ci/actions/?h=github+act#usage
      - name: Publish via GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
