name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-macos:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: ovt
            asset_name: ouverture-macos-amd64

    steps:
      - name: Build
        run: swift build -c release

      - name: Zip
        run: tar czvf ${{ matrix.asset_name }}.tar.gz -C ./.build/release ${{ matrix.artifact_name }}

      - name: Generate sha256
        run: openssl dgst -r -sha256 ${{ matrix.asset_name }}.tar.gz > ${{ matrix.asset_name }}.tar.gz.sha256

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload sha256 to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.tar.gz.sha256
          asset_name: ${{ matrix.asset_name }}.tar.gz.sha256
          tag: ${{ github.ref }}
          overwrite: true

  bump-tap-version:
    name: Generate new ruby script for homebrew tap
    needs: [publish-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i @actions/core @actions/github

      - name: Get "version"
        id: ver
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check "version"
        env:
          RELEASE_VERSION: ${{ steps.ver.outputs.tag }}
        run: |
          echo "Detected version:"
          echo $RELEASE_VERSION
      - name: Get tarball file name
        id: binaries
        env:
          BIN_MAC: ouverture-macos-amd64.tar.gz
        run: |
          echo ::set-output name=mac::$BIN_MAC
      - name: Get url
        id: url
        env:
          URL_MAC: https://github.com/${{ github.repository }}/releases/download/${{ steps.ver.outputs.tag }}/${{ steps.binaries.outputs.mac }}
        run: |
          echo ::set-output name=mac::$URL_MAC
      - name: Get files and checksums
        id: checksums
        run: |
          curl -LO ${{ steps.url.outputs.mac }}.sha256
          echo ::set-output name=mac::$(cat ${{ steps.binaries.outputs.mac }}.sha256 | awk '{ print $1 }')
      - name: Replace variables in template
        uses: rami3l/bumper@master
        id: replace
        with:
          template: "dist/brew/template.rb"
          out: "ouverture.rb"

          rules: |
            {
              "version": "${{ steps.ver.outputs.tag }}",
              "url_mac": "${{ steps.url.outputs.mac }}",
              "sha256_mac": "${{ steps.checksums.outputs.mac }}",
            }
      - name: Get the output script
        run: cat ouverture.rb

      - name: Upload the script to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "ouverture.rb"
          asset_name: "ouverture.rb"
          tag: ${{ github.ref }}
          overwrite: true
