# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1

      # src: https://harry.garrood.me/blog/easy-incremental-haskell-ci-builds-with-ghc-9.4/
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            .build
          key: build-${{ runner.os }}-${{ hashFiles('Package.swift') }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            build-${{ runner.os }}-${{ hashFiles('Package.swift') }}

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
